repos:
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        language_version: python3
  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
        language_version: python3
  - repo: https://github.com/pycqa/flake8
    rev: 4.0.1
    hooks:
      - id: flake8
  - repo: https://github.com/econchick/interrogate
    rev: 1.5.0
    hooks:
      - id: interrogate
        args: [-vv]
        pass_filenames: false
  - repo: https://github.com/fsouza/autoflake8
    rev: v0.3.2
    hooks:
      - id: autoflake8
        language_version: python3
        args: [
          '--in-place',
        ]
