name: Add issues to integrations board

on:
  issues:
    types:
      - opened

jobs:

  add-to-project:
    name: Add issue to project
    runs-on: ubuntu-latest
    steps:
      - uses: tibdex/github-app-token@v1
        id: generate-token
        name: Generate GitHub token
        with:
          app_id: ${{ secrets.SYNC_APP_ID }}
          private_key: ${{ secrets.SYNC_APP_PRIVATE_KEY }}

      - uses: actions/add-to-project@v0.4.0
        with:
          project-url: ${{ secrets.ADD_TO_PROJECT_URL }}
          github-token: ${{ steps.generate-token.outputs.token }}
